In [2]:
import pandas as pd

df = pd.read_csv('data/datos_delitos.csv', encoding='latin1')

In [3]:
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,20,22,34,35,34,37,NaN,NaN,NaN,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,NaN,NaN,NaN,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,183,174,199,208,177,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31360 entries, 0 to 31359
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     31360 non-null  int64
 1   Clave_Ent               31360 non-null  int64
 2   Entidad                 31360 non-null  str
 3   Bien jurídico afectado  31360 non-null  str
 4   Tipo de delito          31360 non-null  str
 5   Subtipo de delito       31360 non-null  str
 6   Modalidad               31360 non-null  str
 7   Enero                   31360 non-null  int64
 8   Febrero                 31360 non-null  int64
 9   Marzo                   31360 non-null  int64
 10  Abril                   31360 non-null  int64
 11  Mayo                    31360 non-null  int64
 12  Junio                   31360 non-null  int64
 13  Julio                   28224 non-null  float64
 14  Agosto                  28224 non-null  float64
 15  Septiembre              28224 non-null  float64
 16  Octubre                 28224 non-null  float64
 17  Noviembre               28224 non-null  float64
 18  Diciembre               28224 non-null  float64
dtypes: float64(6), int64(8), str(5)
memory usage: 4.5 MB

In [6]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [7]:
len(df.columns)

19

In [8]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)
    
    df.columns = columnas_limpias
    
    return df
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [9]:
df = limpiar_columnas(df)

In [10]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0

In [11]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
31355  2024       Zacatecas
31356  2024       Zacatecas
31357  2024       Zacatecas
31358  2024       Zacatecas
31359  2024       Zacatecas

[31360 rows x 2 columns]

In [12]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [13]:
print("Shape ", df.shape)

Shape  (31360, 18)

In [14]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [15]:
print("Shape: ", datos_long.shape)

Shape:  (376320, 8)

In [16]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1.0
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0.0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2.0
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0.0

In [17]:
datos_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 376320 entries, 0 to 376319
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               376320 non-null  int64
 1   clave_ent          376320 non-null  int64
 2   entidad            376320 non-null  str
 3   tipo_de_delito     376320 non-null  str
 4   subtipo_de_delito  376320 non-null  str
 5   modalidad          376320 non-null  str
 6   nombre_mes         376320 non-null  str
 7   frecuencia         357504 non-null  float64
dtypes: float64(1), int64(2), str(5)
memory usage: 23.0 MB

In [18]:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [19]:
datos_long[datos_long.tipo_de_delito == 'Robo'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
113675,2022,13,Hidalgo,Robo,septiembre,1139.0
75267,2019,29,Tlaxcala,Robo,enero,298.0
85827,2020,19,Nuevo León,Robo,enero,1493.0
81505,2020,10,Durango,Robo,agosto,747.0
100233,2021,17,Morelos,Robo,noviembre,1243.0
127587,2023,10,Durango,Robo,enero,397.0
141987,2024,8,Chihuahua,Robo,enero,1335.0
18632,2016,7,Chiapas,Robo,mayo,736.0
87271,2020,22,Querétaro,Robo,marzo,2074.0
122785,2022,32,Zacatecas,Robo,agosto,538.0
119433,2022,25,Sinaloa,Robo,noviembre,700.0
134790,2023,25,Sinaloa,Robo,junio,752.0
46955,2018,2,Baja California,Robo,septiembre,3094.0
145833,2024,16,Michoacán de Ocampo,Robo,noviembre,0.0
81032,2020,9,Ciudad de México,Robo,mayo,4549.0

In [20]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
480            2                  Baja California
960            3              Baja California Sur
1440           4                         Campeche
2880           7                          Chiapas
3360           8                        Chihuahua
3840           9                 Ciudad de México
1920           5             Coahuila de Zaragoza
2400           6                           Colima
4320          10                          Durango
4800          11                       Guanajuato
5280          12                         Guerrero
5760          13                          Hidalgo
6240          14                          Jalisco
7200          16              Michoacán de Ocampo
7680          17                          Morelos
6720          15                           México
8160          18                          Nayarit
8640          19                       Nuevo León
9120          20                           Oaxaca
9600          21                           Puebla
10080         22                        Querétaro
10560         23                     Quintana Roo
11040         24                  San Luis Potosí
11520         25                          Sinaloa
12000         26                           Sonora
12480         27                          Tabasco
12960         28                       Tamaulipas
13440         29                         Tlaxcala
13920         30  Veracruz de Ignacio de la Llave
14400         31                          Yucatán
14880         32                        Zacatecas

In [21]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
147359,2024,19,Nuevo León,Violencia familiar,septiembre,0.0
100974,2021,19,Nuevo León,Falsedad,junio,14.0
101078,2021,19,Nuevo León,Narcomenudeo,diciembre,356.0
116220,2022,19,Nuevo León,Amenazas,abril,523.0
100832,2021,19,Nuevo León,Abuso sexual,mayo,160.0
131580,2023,19,Nuevo León,Amenazas,abril,441.0
147121,2024,19,Nuevo León,Incesto,agosto,0.0
39496,2017,19,Nuevo León,Electorales,febrero,0.0
116436,2022,19,Nuevo León,Narcomenudeo,abril,447.0
24246,2016,19,Nuevo León,Incesto,junio,0.0
8800,2015,19,Nuevo León,Extorsión,febrero,59.0
54980,2018,19,Nuevo León,Incumplimiento de obligaciones de asistencia f...,mayo,51.0
8957,2015,19,Nuevo León,Otros delitos contra la sociedad,julio,0.0
131597,2023,19,Nuevo León,Contra el medio ambiente,julio,4.0
147056,2024,19,Nuevo León,Falsedad,mayo,16.0

In [22]:
datos_long[(datos_long['clave_ent'] > 19) &  (datos_long['clave_ent'] < 24) & (datos_long['tipo_de_delito'] == 'Homicidio')].sample(15)

        anio  clave_ent       entidad tipo_de_delito  nombre_mes  frecuencia
101985  2021         21        Puebla      Homicidio   noviembre       101.0
116865  2022         20        Oaxaca      Homicidio   noviembre       155.0
86141   2020         20        Oaxaca      Homicidio       julio       108.0
86619   2020         21        Puebla      Homicidio       enero       116.0
148063  2024         21        Puebla      Homicidio       marzo       160.0
10303   2015         22     Querétaro      Homicidio       marzo        36.0
117821  2022         22     Querétaro      Homicidio       julio        47.0
71266   2019         21        Puebla      Homicidio     octubre       136.0
101979  2021         21        Puebla      Homicidio       enero        86.0
87576   2020         23  Quintana Roo      Homicidio       abril        98.0
55899   2018         21        Puebla      Homicidio       enero       148.0
86623   2020         21        Puebla      Homicidio       marzo       121.0
10779   2015         23  Quintana Roo      Homicidio       enero        38.0
101507  2021         20        Oaxaca      Homicidio  septiembre       128.0
147585  2024         20        Oaxaca      Homicidio   noviembre         0.0

In [23]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero') 
]

        anio  clave_ent entidad tipo_de_delito nombre_mes  frecuencia
147579  2024         20  Oaxaca      Homicidio      enero       157.0

In [24]:
datos_long.sample(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
47287,2018,3,Baja California Sur,Incesto,marzo,0.0
43559,2017,27,Tabasco,Otros delitos que atentan contra la libertad y...,septiembre,39.0

In [25]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna
118245,2022,23,Quintana Roo,Extorsión,noviembre,10.0,dato vacío
30959,2017,1,Aguascalientes,Hostigamiento sexual,septiembre,4.0,dato vacío
147374,2024,20,Oaxaca,Abuso de confianza,diciembre,0.0,dato vacío
78616,2020,4,Campeche,Rapto,febrero,0.0,dato vacío
147757,2024,20,Oaxaca,Secuestro,agosto,0.0,dato vacío
18950,2016,8,Chihuahua,Hostigamiento sexual,diciembre,8.0,dato vacío

In [26]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
59051,2018,28,Tamaulipas,Aborto,septiembre,4.0,dato vacío,9
11737,2015,25,Sinaloa,Homicidio,agosto,123.0,dato vacío,8
19447,2016,9,Ciudad de México,Incesto,marzo,0.0,dato vacío,3
81521,2020,10,Durango,Secuestro,julio,0.0,dato vacío,7
15285,2015,32,Zacatecas,Secuestro,noviembre,0.0,dato vacío,11

In [27]:
datos_long["frecuencia_mas_10"] = datos_long["frecuencia"] + 10
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10
69115,2019,16,Michoacán de Ocampo,Violencia familiar,marzo,91.0,dato vacío,3,101.0
104858,2021,27,Tabasco,Homicidio,diciembre,73.0,dato vacío,12,83.0
90625,2020,29,Tlaxcala,Robo,agosto,265.0,dato vacío,8,275.0
88175,2020,24,San Luis Potosí,Otros delitos del Fuero Común,septiembre,189.0,dato vacío,9,199.0
44000,2017,28,Tamaulipas,Otros delitos contra la sociedad,mayo,0.0,dato vacío,5,10.0

In [28]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes
20327,2016,11,Guanajuato,Extorsión,septiembre,1.0,dato vacío,9,11.0,20169
116584,2022,19,Nuevo León,Tráfico de menores,febrero,0.0,dato vacío,2,10.0,20222
16312,2016,2,Baja California,Violencia familiar,febrero,661.0,dato vacío,2,671.0,20162
133707,2023,23,Quintana Roo,Lesiones,enero,424.0,dato vacío,1,434.0,20231
92434,2021,1,Aguascalientes,Lesiones,octubre,374.0,dato vacío,10,384.0,202110
125493,2023,6,Colima,Fraude,noviembre,193.0,dato vacío,11,203.0,202311

In [29]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes,fecha
7367,2015,16,Michoacán de Ocampo,Extorsión,septiembre,3.0,dato vacío,9,13.0,20159,2015-09-01
6666,2015,14,Jalisco,Tráfico de menores,junio,0.0,dato vacío,6,10.0,20156,2015-06-01
79221,2020,6,Colima,Abuso de confianza,noviembre,34.0,dato vacío,11,44.0,202011,2020-11-01
142216,2024,9,Ciudad de México,Electorales,febrero,58.0,dato vacío,2,68.0,20242,2024-02-01
88116,2020,24,San Luis Potosí,Narcomenudeo,abril,135.0,dato vacío,4,145.0,20204,2020-04-01

In [30]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
88337,2020,25,Sinaloa,Abuso de confianza,julio,24.0,7,34.0,20207,2020-07-01
66679,2019,11,Guanajuato,Violación equiparada,marzo,3.0,3,13.0,20193,2019-03-01
116737,2022,20,Oaxaca,Daño a la propiedad,agosto,239.0,8,249.0,20228,2022-08-01
129050,2023,13,Hidalgo,Trata de personas,diciembre,1.0,12,11.0,202312,2023-12-01
140727,2024,6,Colima,Corrupción de menores,enero,0.0,1,10.0,20241,2024-01-01

In [31]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
147579,2024,20,Oaxaca,Homicidio,enero,157.0,1,167.0,20241,2024-01-01
147580,2024,20,Oaxaca,Homicidio,febrero,170.0,2,180.0,20242,2024-02-01
147583,2024,20,Oaxaca,Homicidio,marzo,190.0,3,200.0,20243,2024-03-01
147576,2024,20,Oaxaca,Homicidio,abril,208.0,4,218.0,20244,2024-04-01
147584,2024,20,Oaxaca,Homicidio,mayo,236.0,5,246.0,20245,2024-05-01
147582,2024,20,Oaxaca,Homicidio,junio,202.0,6,212.0,20246,2024-06-01
147581,2024,20,Oaxaca,Homicidio,julio,0.0,7,10.0,20247,2024-07-01
147577,2024,20,Oaxaca,Homicidio,agosto,0.0,8,10.0,20248,2024-08-01
147587,2024,20,Oaxaca,Homicidio,septiembre,0.0,9,10.0,20249,2024-09-01
147586,2024,20,Oaxaca,Homicidio,octubre,0.0,10,10.0,202410,2024-10-01
147585,2024,20,Oaxaca,Homicidio,noviembre,0.0,11,10.0,202411,2024-11-01
147578,2024,20,Oaxaca,Homicidio,diciembre,0.0,12,10.0,202412,2024-12-01

In [32]:
datos_finales = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales.head(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,abril,2015-04-01,0.0
1,2015,1,Aguascalientes,Aborto,agosto,2015-08-01,0.0

In [33]:
datos_finales.to_csv('data/delitos.csv', index=False)